
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'ED95A2C69A96343D2DE49C13D969203B'
    
_lr_action_items = {'INTEGER':([0,],[3,]),'FLOAT':([0,],[2,]),'$end':([1,2,3,],[0,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> INTEGER','expr',1,'p_expression_number','plyyacc.py',15),
  ('expr -> FLOAT','expr',1,'p_expression_number','plyyacc.py',16),
]
