
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '7E1CD79CC9A0DE663FDAEC7D64226F4C'
    
_lr_action_items = {'RPAREN':([1,3,5,10,11,12,13,14,15,],[-3,-2,-1,15,-7,-4,-5,-6,-8,]),'LOCALID':([0,4,6,7,8,9,],[1,1,1,1,1,1,]),'FLOAT':([0,4,6,7,8,9,],[3,3,3,3,3,3,]),'TIMES':([1,2,3,5,10,11,12,13,14,15,],[-3,9,-2,-1,9,-7,9,9,-6,-8,]),'PLUS':([1,2,3,5,10,11,12,13,14,15,],[-3,7,-2,-1,7,-7,-4,-5,-6,-8,]),'LPAREN':([0,4,6,7,8,9,],[4,4,4,4,4,4,]),'INTEGER':([0,4,6,7,8,9,],[5,5,5,5,5,5,]),'$end':([1,2,3,5,11,12,13,14,15,],[-3,0,-2,-1,-7,-4,-5,-6,-8,]),'MINUS':([1,2,3,5,10,11,12,13,14,15,],[-3,8,-2,-1,8,-7,-4,-5,-6,-8,]),'DIVIDE':([1,2,3,5,10,11,12,13,14,15,],[-3,6,-2,-1,6,-7,6,6,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,6,7,8,9,],[2,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> INTEGER','expr',1,'p_expression_number','plyyacc.py',15),
  ('expr -> FLOAT','expr',1,'p_expression_number','plyyacc.py',16),
  ('expr -> LOCALID','expr',1,'p_expression_localid','plyyacc.py',20),
  ('expr -> expr PLUS expr','expr',3,'p_expression_binary','plyyacc.py',24),
  ('expr -> expr MINUS expr','expr',3,'p_expression_binary','plyyacc.py',25),
  ('expr -> expr TIMES expr','expr',3,'p_expression_binary','plyyacc.py',26),
  ('expr -> expr DIVIDE expr','expr',3,'p_expression_binary','plyyacc.py',27),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expression_group','plyyacc.py',31),
]
